### ISSUE TITLE
Getting error "sqlserverport.sqlserverport.BrowserError: No response from SQL Browser service"

### ISSUE THREAD

**Issue by prate2012** [gordthompson/sqlserverport#2]
Hi @gordthompson ,

We used sqlserverport in a python based cron job deployed in AKS. Trying to connect to named SQL server instance with port 49002.

It did work in one environment but when moving to other environment when we are trying same it gave below error in the logs

_sqlserverport.sqlserverport.BrowserError: No response from SQL Browser service.Verify that the service is available on <<servername>> and \<<instancename>> is a valid instance name on it._

We tried servername as below but none of them are working
1.fullyqualifieddns,portnumber
2.only servername without suffix of .com
3. Ip address of server (xxx.xxx.xxx.xxx)

Could you please help us here?

**Comment by gordthompson** [comment]
> Trying to connect to named SQL server instance with port 49002.

Do you mean that the SQL Server instance is listening on port 49002? If so, then you don't need to use sqlserverport because you already know what port number to use.

**Comment by prate2012** [comment]
@gordthompson  - We are using sqlserver port because its a Named SQL server instance that Linux based AKS cronjob trying to connect

**Comment by gordthompson** [comment]
So what does "port 49002" refer to?

**Comment by prate2012** [comment]
@gordthompson -For egress connection from AKS to on-prem SQL instances, we use 1433,49001,49002 etc ports. 

Below is the splunk log which we are seeing. 

<img width="674" alt="image" src="https://github.com/user-attachments/assets/8d3eeb51-6067-424b-ad28-a964fad5f334">

**Comment by prate2012** [comment]
@gordthompson  - Is it getting connection timedout due to max size of bytes i.e 1024 as we can see in splunk log , it has reference to sqlserverport.py,line 61

_response = sock.recv(1024)  # max 1024 bytes for CLNT_UCAST_INST_

**Comment by gordthompson** [comment]
So a process somewhere in the cloud is trying to connect from its outbound port 49002 to the SQL Browser service (UDP port 1434) on one of your on-prem servers. Is that correct?

**Comment by prate2012** [comment]
@gordthompson - Yes that is right,as it is giving below exception. Is there a way i can increase timeout ?

it is giving 

 _except socket.timeout as no_response:
        raise BrowserError(
            r"No response from the SQL Browser service. "
            r"Verify that the service is available on "
            r"{0} and \{1} is a valid instance name on it.".format(
                server, instance
            )
        )_

**Comment by gordthompson** [comment]
You could try increasing the value here

https://github.com/gordthompson/sqlserverport/blob/c7829dfa3e1327353b3b4f6078b0bc2a00166ca7/sqlserverport/sqlserverport.py#L56

**Comment by prate2012** [comment]
@gordthompson - i have imported sqlserverport in other application and referring as per example.

How can I set "sock.settimeout(5)" in such case?

**Comment by gordthompson** [comment]
If you installed using `pip install sqlserverport` then the sqlserverport.py file will be under site-packages folder for your Python environment. For my virtual environment, it is

```
/home/gord/.virtualenvs/venv/lib/python3.12/site-packages/sqlserverport/sqlserverport.py
```

**Comment by prate2012** [comment]
@gordthompson - would it be possible for you to update  _sock.settimeout(5)_  to say 20 seconds and publish it?

**Comment by gordthompson** [comment]
Fork this repo. In the master branch of your fork, update line 56 in sqlserverport.py with your new timeout value. Then, instead of

```
pip install sqlserverport
```

use

```
pip install git+https://github.com/prate2012/sqlserverport.git
```

**Comment by gordthompson** [comment]
Were you able to change the timeout value, and if so, did it resolve your issue?

**Comment by prate2012** [comment]
No but we did allow 1434 port which fixed the issue
